from .parallelSystem_experiment import ParallelSystemExperimentFrame
from .serialSystem_expirement import SerialSystemExperimentFrame
from .serialSystem_research import SerialSystemResearchFrame
from .parallelSystem_research import ParallelSystemResearchFrame
